# Generated by Django 4.0.3 on 2022-05-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_email_contact_email_rename_name_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='webservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('ip1', models.CharField(max_length=200)),
                ('ip2', models.CharField(max_length=200)),
                ('ip3', models.CharField(max_length=200)),
                ('ip4', models.CharField(max_length=200)),
                ('ip5', models.CharField(max_length=200)),
                ('ip6', models.CharField(max_length=200)),
                ('ip7', models.CharField(max_length=200)),
                ('ip8', models.CharField(max_length=200)),
                ('ip9', models.CharField(max_length=200)),
                ('ip10', models.CharField(max_length=200)),
            ],
        ),
    ]
