# Generated by Django 4.0.3 on 2022-05-31 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_webservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webservices',
            new_name='Webservice',
        ),
    ]
