# Generated by Django 4.0.3 on 2022-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebBeta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('ip1', models.CharField(max_length=200)),
                ('ip2', models.CharField(max_length=200)),
                ('ip3', models.CharField(max_length=200)),
                ('ip4', models.CharField(max_length=200)),
                ('ip5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebBeta2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('ip1', models.CharField(max_length=200)),
                ('ip2', models.CharField(max_length=200)),
                ('ip3', models.CharField(max_length=200)),
                ('ip4', models.CharField(max_length=200)),
                ('ip5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebBeta3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('ip1', models.CharField(max_length=200)),
                ('ip2', models.CharField(max_length=200)),
                ('ip3', models.CharField(max_length=200)),
                ('ip4', models.CharField(max_length=200)),
                ('ip5', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WebBeta4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('ip1', models.CharField(max_length=200)),
                ('ip2', models.CharField(max_length=200)),
                ('ip3', models.CharField(max_length=200)),
                ('ip4', models.CharField(max_length=200)),
                ('ip5', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Webservice',
        ),
    ]
