# Generated by Django 4.0.3 on 2022-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_webbeta1_webbeta2_webbeta3_webbeta4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webbeta1',
            name='ip1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta1',
            name='ip2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta1',
            name='ip3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta1',
            name='ip4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta1',
            name='ip5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta2',
            name='ip1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta2',
            name='ip2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta2',
            name='ip3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta2',
            name='ip4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta2',
            name='ip5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta3',
            name='ip1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta3',
            name='ip2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta3',
            name='ip3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta3',
            name='ip4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta3',
            name='ip5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta4',
            name='ip1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta4',
            name='ip2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta4',
            name='ip3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta4',
            name='ip4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='webbeta4',
            name='ip5',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
