# Generated by Django 4.0.6 on 2023-02-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_newupdateinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
