# Generated by Django 4.1.7 on 2023-03-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_rrfimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rrfimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
